version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

orbs:
  maven: circleci/maven@1.2.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - build:
          context: SonarCloud
